[package]
name = "tproc"
version = "0.1.0"
authors = ["Michal Hornicky <mhornick@redhat.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
anyhow = "1.0.34"
csv = "1.1.4"

rust_decimal = { version = "1.8.1", features = ["serde-float"] }
